---
servers:
- url: "http://localhost:8080"
openapi: "3.0.3"
paths:
  /entitlement-api/v1/entitlements/{entitlement}:
    $ref: "./openapi/entitlement-api.yaml#/paths/~1entitlement-api~1v1~1entitlements~1{entitlement}"
  /audit-api/v1/events:
    $ref: "./openapi/audit-api.yaml#/paths/~1audit-api~1v1~1events"
  /entitlement-api/v1/entitlements:
    $ref: "./openapi/entitlement-api.yaml#/paths/~1entitlement-api~1v1~1entitlements"
  /audit-api/v1/about:
    $ref: "./openapi/audit-api.yaml#/paths/~1audit-api~1v1~1about"
  /entitlement-api/v1/about:
    $ref: "./openapi/entitlement-api.yaml#/paths/~1entitlement-api~1v1~1about"
  /audit-api/v1/events/{event}:
    $ref: "./openapi/audit-api.yaml#/paths/~1audit-api~1v1~1events~1{event}"
info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"
